import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Common/Nav";
import Header from "@/components/Common/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#141414]`}
      >
        <div className="flex h-screen text-white overflow-hidden">
          <Nav />

          <main className="flex-1 overflow-y-auto">
            <Header />

            <div className="px-6 pb-6">
              <div className="grid gap-6 p-4">
                {children}
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
